version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-todo
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      # Optionally mount init scripts
      # - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
