[package]
name = "pulsar-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
pulsar = "6.3.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1", features = ["full"] }
