version: "3.9"

services:
  pulsar:
    image: apachepulsar/pulsar
    container_name: pulsar
    command: >
      bin/pulsar standalone
    ports:
      - "6650:6650" # Pulsar binary protocol port
      - "8080:8080" # Pulsar admin console port
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-conf:/pulsar/conf

volumes:
  pulsar-data:
  pulsar-conf:
