[package]
name = "neo4j-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
chrono = "0.4.39"
dotenv = "0.15.0"
neo4j = "0.1.0"
neo4rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.134"
uuid = { version = "1.1", features = ["v4"] }
