version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_instance
    ports:
      # Bolt protocol port
      - "7687:7687"
      # HTTP port
      - "7474:7474"
      # HTTPS port
      - "7473:7473"
    volumes:
      # Data persistence
      - neo4j_data:/data
      # Database dumps and imports
      - neo4j_imports:/var/lib/neo4j/import
      # Database backups
      - neo4j_backups:/backups
      # Plugins directory
      - neo4j_plugins:/plugins
      # Logs directory
      - neo4j_logs:/logs
    environment:
      # Accept license agreement
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Initial password for neo4j user
      - NEO4J_AUTH=neo4j/password
      # Memory settings
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # Enable GDS library
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      # Enable APOC
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      # Enable remote connections
      - NEO4J_server_default__listen__address=0.0.0.0
      # Configure logging
      - NEO4J_dbms_logs_debug_level=INFO
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - neo4j_network

volumes:
  neo4j_data:
  neo4j_imports:
  neo4j_backups:
  neo4j_plugins:
  neo4j_logs:


networks:
  neo4j_network:
    driver: bridge
