version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt protocol
    environment:
      # Admin credentials
      - NEO4J_AUTH=neo4j/your_secure_password_here

      # Enable remote connections (be cautious; restrict access for production)
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_default__advertised__address=localhost

      # Performance optimizations
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G

      # Logging configuration
      - NEO4J_dbms_logs_debug_level=INFO

      # Optional: Enable APOC library
      - NEO4JLABS_PLUGINS=["apoc"]

      # Optional: Enable Bloom (Graph Visualization Tool)
      - NEO4JLABS_PLUGINS=["bloom"]

      # Configure backups (use external backup service)
      - NEO4J_dbms_backup_enabled=true

      # Enable metrics for monitoring (Prometheus compatible)
      - NEO4J_dbms_metrics_enabled=true

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    networks:
      - neo4j_network

networks:
  neo4j_network:
    driver: bridge

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
